### ISSUE TITLE
CMake Build에서 에러가 납니다

### ISSUE THREAD

**Issue by heeeete** [chcbaram/baram-qmk-8k#10]
m1 mac 입니다. 어떻게 해야 하나요???

[100%] Linking CXX executable baram-qmk-8k.elf
/Applications/ArmGNUToolchain/13.3.rel1/arm-none-eabi/bin/../lib/gcc/arm-none-eabi/13.3.1/../../../../arm-none-eabi/bin/ld: CMakeFiles/baram-qmk-8k.elf.dir/src/ap/modules/qmk/port/matrix.c.obj: in function `matrix_init':
/Users/huipark/baram-qmk-8k/src/ap/modules/qmk/port/matrix.c:31:(.text.matrix_init+0x16): undefined reference to `debounce_init'
/Applications/ArmGNUToolchain/13.3.rel1/arm-none-eabi/bin/../lib/gcc/arm-none-eabi/13.3.1/../../../../arm-none-eabi/bin/ld: CMakeFiles/baram-qmk-8k.elf.dir/src/ap/modules/qmk/port/matrix.c.obj: in function `matrix_scan':
/Users/huipark/baram-qmk-8k/src/ap/modules/qmk/port/matrix.c:97:(.text.matrix_scan+0x194): undefined reference to `debounce'
Memory region         Used Size  Region Size  %age Used
             RAM:       77456 B      2496 KB      3.03%
           SRAM4:           0 B        16 KB      0.00%
          VECTOR:         592 B         1 KB     57.81%
             VER:          72 B         1 KB      7.03%
           FLASH:        148 KB       509 KB     29.08%
collect2: error: ld returned 1 exit status
make[2]: *** [baram-qmk-8k.elf] Error 1
make[1]: *** [CMakeFiles/baram-qmk-8k.elf.dir/all] Error 2
make: *** [all] Error 2

**Comment by chcbaram** [comment]
현재 메인 브렌치에 BARAM 키보드 쪽은 디바운스 옵션 수정이 안되어 있어서 빌드 오류가 납니다. 
anti-ghost 브렌치로 다시 빌드 해 보시면 됩니다. 
https://github.com/chcbaram/baram-qmk-8k/tree/anti-ghost

혹은 아래 링크 내용처럼 cmake에 디바운스 옵션 추가하시면 됩니다. 
https://github.com/chcbaram/baram-qmk-8k/blob/7e5254f01ddf29fc76fe070ba80e56f6eb9f1431/src/ap/modules/qmk/keyboards/geon/VENOM-60MX-7U/config.cmake#L7

**Comment by heeeete** [comment]
감사합니다 해볼게요 혹시 빌드한걸 적용 시키는 건 그 esc 눌러서 포트 꼽고 드라이브에 넣으면 되는건가요?

**Comment by chcbaram** [comment]
네 생성된 uf2 파일을 넣으면 되는데, 보드에 맞는 모델로 빌드해야 합니다. 다른 모델 펌웨어를 다운로두 하면 정상동작 하지 않습니다.

2024년 8월 16일 (금) 오후 11:02, heeeete ***@***.***>님이 작성:

**Comment by heeeete** [comment]
감사합니다 혹시나 잘못 넣을 경우 초기화나 이런건 작동 안 하고 보드에 맞는 uf2를 다시 넣어야 하는거죠??

**Comment by heeeete** [comment]
VENOM60MX 7u 를 환경변수로 넣어주려는데 에러가 나는데 이건 어떻게 해결하나요?...

```
~/baram-qmk-8k/prj/vscode (anti-ghost) » cmake -S . -B build -DKEYBOARD_PATH='/keyboards/geon/VENOM-60MX-7U'
CMake Error: The source directory "/Users/huipark/baram-qmk-8k/prj/vscode" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
```

**Comment by heeeete** [comment]
그런데 빌드를 하고 파일명을 보니 마지막에 R2 라고 나오는데 지온웍스 공식 가이드에 있는 uf2는 R1으로 나와있는데 차이가 뭔가요? venom 60 mx 7u 보드입니다. 
그냥 넣어도 되는건가요?

**Comment by chcbaram** [comment]
잘못다운로드 되었을경우 부트로더 진입후에 다시 업데이트 하면 됩니다. 
anti-ghost 브랜치는 테스트 버전으로 R2가 맞습니다.

**Comment by heeeete** [comment]
감사합니다 잘 적용됐습니다.
